### PR TITLE
Change timestamp-task and timestamp-batch 3.0.x to Boot 3.2.8

### PR DESCRIPTION
**Pull request by corneil**
This change updates the current 3.0.x task/batch apps to use Spring Boot 3.2.8. 
The CI will run and publish the apps once this is merged.

The next step is to merge https://github.com/spring-cloud/spring-cloud-dataflow-samples/pull/202 which will bump the version of the task/batch apps to 3.1.x and set those to use Spring Boot 3.3.1.

End result is a set of task/batch apps as follows:
- apps version 3.0 uses boot 3.2.x
- apps version 3.1 uses boot 3.3.x

### CODE REVIEW

**Review by cppwfs — APPROVED** [review]
LGTM

Thanks for looking into this!

**Review by cppwfs — CHANGES_REQUESTED** [review]
hmm.. Why are we going from 3.3.x to 3.2.x

**Comment by onobc** [comment]
> hmm.. Why are we going from 3.3.x to 3.2.x? Do we need to close this PR?

We are missing some context on these PR's @corneil . I have deciphered though that the previous PR is bumping the version of the apps to 3.1.0 (which uses boot 3.3.x) and this PR bumps the current version of the apps 3.0 to Boot 3.2.8.

End result is the following:
- apps version 3.0 uses boot 3.2.x
- apps version 3.1 uses boot 3.3.x

Is this correct? Please add this fact to both PR descrptions.

**Comment by corneil** [comment]
> > hmm.. Why are we going from 3.3.x to 3.2.x? Do we need to close this PR?
> 
> We are missing some context on these PR's @corneil . I have deciphered though that the previous PR is bumping the version of the apps to 3.1.0 (which uses boot 3.3.x) and this PR bumps the current version of the apps 3.0 to Boot 3.2.8.
> 
> End result is the following:
> 
> * apps version 3.0 uses boot 3.2.x
> * apps version 3.1 uses boot 3.3.x
> 
> Is this correct? Please add this fact to both PR descrptions.

The PR for 3.0.0 should be merged and then the PR for 3.1.0 so that we jave 2 v3 based artifacts of timestamp task and batch for use in tests.

**Comment by corneil** [comment]
> hmm.. Why are we going from 3.3.x to 3.2.x? Do we need to close this PR?

To have something that distinguishes 3.0 and 3.1

**Comment by onobc** [comment]
> > > hmm.. Why are we going from 3.3.x to 3.2.x? Do we need to close this PR?
> > 
> > 
> > We are missing some context on these PR's @corneil . I have deciphered though that the previous PR is bumping the version of the apps to 3.1.0 (which uses boot 3.3.x) and this PR bumps the current version of the apps 3.0 to Boot 3.2.8.
> > End result is the following:
> > 
> > * apps version 3.0 uses boot 3.2.x
> > * apps version 3.1 uses boot 3.3.x
> > 
> > Is this correct? Please add this fact to both PR descrptions.
> 
> The PR for 3.0.0 should be merged and then the PR for 3.1.0 so that we jave 2 v3 based artifacts of timestamp task and batch for use in tests.

My point is that a few sentences in the PRs description would have avoided this discussion and time spent figuring out what they are doing. The missing piece being that the CI runs and publishes the apps (hence the need for 2 separate movements). Had the description been something like [this](https://github.com/spring-cloud/spring-cloud-dataflow-samples/pull/201#issue-2538904554) someone would have just pushed the green merge button when they saw it the first time. :)

**Review by cppwfs — APPROVED** [review]
After the dialogue with @onobc and @corneil , I understand the flow.  Thanks!

**Pull request merged**
