### PR TITLE
Consolidated stream samples -  updated and function based

### PR DESCRIPTION
**Pull request by dturanski**
Consolidate rabbit and kafka samples into a single code base.  DO NOT MERGE until dataflow.spring.io is updated to reflect this change.

### CODE REVIEW

**Comment by dturanski** [comment]
see https://github.com/spring-io/dataflow.spring.io/pull/349

**Comment by dturanski** [comment]
Following merge, we need to update the CI plan https://build.spring.io/build/admin/edit/editBuildTasks.action?buildKey=SCD-SCDFSAMPLES-JOB1 . Pom changes will also be required.

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
This change missed a jib plugin config to push the images. Fixed via f2b8d5b

**Comment by ilayaperumalg** [comment]
The CI plan https://build.spring.io/browse/SCD-SCDFSAMPLES-JOB1-214 is updated to publish both the maven artifacts and docker images.

**Pull request merged**
